### ISSUE TITLE
Docs: env var fallback for API keys

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo-action#120]
I am pretty sure these are equivalent:

```yaml
      - uses: promptfoo/promptfoo-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          ...
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
```

Can we document that it's possible to use env vars, instead of `openai-api-key`/`anthropic-api-key` args themselves for API keys?
