### ISSUE TITLE
Crash when trying to make output file: nonexistent directory

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo-action#123]
When using `promptfoo-action` v1, I got this crash after `promptfoo eval` ran:

```none
Writing output to /home/runner/work/repo/repo/output.json
Error running database migrations: Cannot open database because the directory does not exist
======================================================================
/home/runner/.npm/_npx/abc123/node_modules/better-sqlite3/lib/database.js:65
		throw new TypeError('Cannot open database because the directory does not exist');
		      ^
```

For some reason, it tried to use a subdirectory. I am not sure what happened. Here is my GitHub Action YAML:

```yaml
      - uses: promptfoo/promptfoo-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompts: litqa-v1*.jsonl # Workaround for https://github.com/promptfoo/promptfoo-action/issues/122
          config: .github/promptfooconfig.yaml
          cache-path: ~/.cache/promptfoo
          use-config-prompts: true
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPTFOO_DISABLE_TELEMETRY: 1
          PROMPTFOO_DISABLE_UPDATE: 1
```

I ran `pwd` right before invoking `promptfoo/promptfoo-action`, and it outputs: `/home/runner/work/repo/repo`

**Comment by jamesbraza** [comment]
Adding:

```yaml
    permissions:
      contents: read # Required for actions/checkout
      pull-requests: write # Ability to post comments on Pull Requests
```

Or:

```yaml
    permissions:
      contents: write # Required for actions/checkout
      pull-requests: write # Ability to post comments on Pull Requests
```

Did not resolve this error

**Comment by typpo** [comment]
hmm, try setting the `PROMPTFOO_CONFIG_DIR` environment variable to a specific folder that you know exists and is writeable from the test runner.

**Comment by jamesbraza** [comment]
What I did was run `mkdir ~/.promptfoo` and the issue has been resolved.

```yaml
      - name: Set up for promptfoo-action
        # Create default PROMPTFOO_CONFIG_DIR to work
        # around https://github.com/promptfoo/promptfoo-action/issues/123
        run: mkdir ~/.promptfoo
      - uses: promptfoo/promptfoo-action@v1
        with:
          ...
```

Do you think this should be added to `promptfoo-action` itself?
