### ISSUE TITLE
`fatal: not a git repository` error

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo-action#76]
```yaml
---
name: Prompt Evaluation
on: # yamllint disable-line rule:truthy
    pull_request:

jobs:
    evaluate:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write # Post comments on Pull Requests
        steps:
            - name: Create promptfoo cache
              uses: actions/cache@v3
              with:
                  path: ~/.cache/promptfoo
                  key: ${{ runner.os }}-promptfoo-v1
                  restore-keys: ${{ runner.os }}-promptfoo-
            - name: Run foo evaluation
              uses: typpo/promptfoo-action@v1
              with:
                  github-token: ${{ secrets.<redacted> }}
                  prompts: prompts/foo-prompts.txt
                  config: prompts/foo-config.yaml
                  cache-path: ~/.cache/promptfoo
```

Running the second step `typpo/promptfoo-action@v1`, I get a warning and error:

```none
Warning: Can't add secret mask for empty string in ##[add-mask] command.
/usr/bin/git fetch origin main
fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128
```

I actually am in a Git repository here with a `main` branch present (and using GitHub + GitHub Actions).

Not sure what is happening here

**Comment by typpo** [comment]
Hey @jamesbraza!  Thanks for your patience here.

I'm not totally sure, but it seems like the Action is not running in a valid git repo.  That is strange because it worked ok for me, but maybe that is a side effect of my other actions setup.  Let's try adding a step to checkout your code as the first step:

```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
```
