### ISSUE TITLE
Warning: Can't add secret mask for empty string in ##[add-mask] command.

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo-action#85]
```
Warning: Can't add secret mask for empty string in ##[add-mask] command.
```

This warning shows up when I run this:

```yaml
            - name: Run XYZ evaluation
              uses: promptfoo/promptfoo-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  prompts: prompts/XYZ-prompts.txt
                  config: prompts/XYZ-config.yaml
                  cache-path: ~/.cache/promptfoo
```

Here is the printed output:

```
Run promptfoo/promptfoo-action@v1
  with:
    github-token: ***
    prompts: prompts/XYZ-prompts.txt
    config: prompts/XYZ-config.yaml
    cache-path: ~/.cache/promptfoo
  env:
    PROMPTFOO_DISABLE_TELEMETRY: 1
Warning: Can't add secret mask for empty string in ##[add-mask] command.
/usr/bin/git fetch origin main
From https://github.com/user/repo
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
/usr/bin/git fetch origin my-branch
From https://github.com/user/repo
 * branch            my-branch -> FETCH_HEAD
 * [new branch]      my-branch -> origin/my-branch
```

What is the story with this warning? Can we make it go away 🤓 ?
